### ISSUE TITLE
Methods for ICS class

### ISSUE THREAD

**Issue by AuroreAA** [AuroreAA/ICS#1]
I implemented the following methods: `coef`, `fitted`, `print`, `plot`,` summary` and `screeplot`, as well as the `components.ICS` function as previously done.
For `summary`, I  added the other new arguments for the ICS function. However I have some issues with the `S2_label` when `S2 = cov4` or `S2 = cov4(X)`. For the plots, should we use the same as previously or do them with ggplot? Could you think about other important things?

**Comment by aalfons** [comment]
Thanks! It seems that the command for printing `S2_label` was inside an `if()` clause by mistake. You were probably too close to the code to notice at the time.

There is a bigger issue, however. In general, a `summary()` method should not print anything. It's good practice that `summary()` returns an object, for example of class `"summary_ICS"`, for which we then define a `print()` method. In our case, this may be a bit strange, though, because `summary()` doesn't actually compute anything additional.

In addition, the `print()` method is a bit too stingy with information, as it's not clear what the printed list components are without looking at the help file. I'd suggest that the `print()` method shows the same text for the `lambda` values and `W` matrix as the `summary()` method, with the `summary()` method giving additional details  on the argument values. I'd also suggest that in both cases, more explanation is given what the `W` matrix is.

For the plots, my preference would be to use `ggplot2`, since this is a bit the standard now, and since we are aiming to be more in line with the tidyverse (for example with respect to the naming convention for the new functions).

**Comment by AuroreAA** [comment]
Thanks for solving the bug! 

That's fine with me. @klauschN  what do you think?

**Comment by klauschN** [comment]
About the summary, I also know that it should not "print" anything. But as correctly noted here, we do not compute there anything new which is why I at least let do it print right away.
About the plotting. I agree that ggplot is nowadays the preferred option. But how would that be named - as for me it is still strange that ggplot is not a generic.  Could there be then traditional and ggplots?

**Comment by aalfons** [comment]
Since the bug is fixed and we discussed the rest in our meeting, I'll close this issue now. We can revisit the issue about using `ggplot2` for the plots later on, perhaps in a new issue.
