### ISSUE TITLE
ICS default parameters

### ISSUE THREAD

**Issue by AuroreAA** [AuroreAA/ICS#2]
Improve the settings of the default parameters.

**Comment by aalfons** [comment]
It's not so clear to me what needs to be done. Perhaps we should talk about it tomorrow?

**Comment by AuroreAA** [comment]
Of course, we can discuss it tomorrow. We should decide about the values of the default parameters depending on the scenarios and also improve the code (there are a lot of nested "if").

**Comment by aalfons** [comment]
I went over `ICS()` and `S2_Y()` to handle the default values. I also cleaned up coding style here and there, but not too much. The tests were ok, so I don't think that I messed anything up, but we should check more carefully.

Before we do that, there are other things we need to figure out. I added a bunch of `TODO` comments for things that were unclear to me, possible bugs, unnecessary leftover lines of code, etc. @AuroreAA, can you please check those?

**Comment by aalfons** [comment]
I forgot to mention: I also changed the order of the arguments to match the order in which we need them in the code (and components in the output accordingly). That makes it easier for me to follow and understand the code.

**Comment by aalfons** [comment]
I think that the last remaining issue is how to handle fixing the signs (argument `fix_signs`). That is not particularly relevant, but we may want back-compatibility with `ics()` and `ics2()` in the sense that:
- If we center the data (`center = TRUE`) and `S1_X` and `S2_X` both have a location component, `fix_signs = "scores"` should fix the signs via generalized skewness values computed from those location estimates. This is the same behavior as `ics2()`.
- Otherwise we use skewness values computed from the means and medians, which is the same behavior as `ics()`.

Note that the above implies that the skewness values based on mean/median are used when we apply the QR algorithm (`QR = TRUE`) or apply whitening (`whiten = TRUE`), as we don't have `S2_X` in those cases. This is how it's implemented now. I also implemented that skewness values based on mean/median are used as fallback option if `S1_X` and `S2_X` use the same location estimate.

An alternative would be to allow a third option for `fix_signs` whether skewness values, generalized skewness values, or only the `W` matrix should be used to fix the signs. But I think that this adds unnecessary complication to the code for something that doesn't really matter other than for computational reproducibility.

@AuroreAA and @klauschN, let me know if you agree with this.

**Comment by klauschN** [comment]
I think the suggestion as above sounds good.
