### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AuroreAA** [AuroreAA/ICS#8]
Clarify the documentation for `ICS` function for:

-  `whiten` and  `QR` parameters in case of the default value (which is `NULL` and not logical).
-  `center` mention that the changes are only for the scores not for the `gen_kurtosis`.

**Comment by aalfons** [comment]
Done. @AuroreAA, please check that the wording is now accurate.

**Comment by AuroreAA** [comment]
Thank you! But in fact, I am thinking that I am not sure if people will understand this is only linked to the algorithm used. Should we just replace `whiten` and `QR` with one argument like `algorithm = c("QR", "whiten", "default")`? 

@klauschN can you also have a look please?

**Comment by aalfons** [comment]
Indeed, that would be easier for the user. But I would not call the third option `"default"`, I'd use something like `"naive"` or `"standard"`. What the default algorithm is depends on which scatters are selected, and also other things if I'm not mistaken (I don't remember exactly from the top of my head).

**Comment by AuroreAA** [comment]
I would prefer `"standard"`. But yes, it depends on some specific things but the `"standard"` one can always be computed.

**Comment by klauschN** [comment]
I agree, one argument like algorithm with options "QR", "whiten" and "standard" sound good. Would "whiten" be the order of options then be whiten, standard and QR?

**Comment by AuroreAA** [comment]
I have implemented it and put "whiten" as default, we can discuss it.

Should we add a line to refer to the ICSClust package to let people know there are also new plots available?

**Comment by aalfons** [comment]
> I have implemented it and put "whiten" as default, we can discuss it.

Thinking about it again now, it might be good to have a fourth option `"automatic"` or `NULL`. Here we can select the most stable algorithm depending on what the user has supplied (e.g., QR when applicable, otherwise whitening when applicable, otherwise the standard algorithm).

If we choose `"whiten"` as default, there may be many situations where it's not applicable, and then we have to decide if we want to give a warning and switch to the standard algorithm.

If the user doesn't care, they can just leave the default `"automatic"` or `NULL`. Otherwise, if they know what they are doing, they can select a specific algorithm, and we throw an **error** (instead of a warning) when that algorithm is not applicable.

**Comment by AuroreAA** [comment]
So far, if we choose `whiten` as it is currently implemented it will trigger a warning but the `standard` algorithm is used instead. 

Even if I like the idea to have an `automatic` option, I am not sure which algorithm we should use when ` QR` is applicable. Indeed, even if this algorithm is more numerically stable, it is longer to compute and if you do not have nearly singular issues, the `whiten` algorithm is more than enough.

**Comment by aalfons** [comment]
Ah, I hadn't considered running time. The `automatic` option could also just choose whitening when appropriate, and otherwise the standard algorithm.

My main concern is having a default option that gives a warning in too many instances (when users supply scatter matrices without a location component). But you and @klauschN know better how the package is typically used, so I'll let you judge on how often that might occur, and whether it's worth it to add such an automatic option.

**Comment by klauschN** [comment]
I would not attempt to guess the best algorithm. But I added some extra comment in the help file.
